### ISSUE TITLE
Audio stream does not play on iOS devices

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#148]
The /cadence1 audio stream does not play from cadenceradio.com, nor the direct link to the mountpoint on stream.cadenceradio.com:8000/cadence1

Devices tested on:
- iPad Mini 2
- iPhone XS

Both devices tested the stream using browsers:
- Safari
- Google Chrome

Update: Further, the stream was just tested on a Macbook Pro. The stream works fine in Chrome but not Safari.

**Comment by za419** [comment]
On wifi or via a cell network?

If on wifi, can other devices on the same network access the stream?

**Comment by kenellorando** [comment]
Fails on both wifi and cellular. My Windows, Linux, and Android devices can still access the stream on the same wifi networks.

**Comment by kenellorando** [comment]
iOS only. Just tested on two Macbooks and it works fine.

**Comment by kenellorando** [comment]
Possible solution will try: declare mime type
https://stackoverflow.com/questions/17454722/apple-removed-the-possibility-to-stream-shoutcast-icecast-on-ios-6-only-in-web

**Comment by za419** [comment]
That seems to be live - Does that fix the problem?
