### ISSUE TITLE
Secure the request system

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#150]
The pre-4.0 request system is actually insecure as heck but also kind of funny. Though it was originally developed a year and half ago, reading how it was developed now makes me laugh seeing how amateur-hour it is. It's at least a nice feeling to see that Cadence is still continually improving.

**The pre-4.0 request system:**
1. A user searches a song.
2. Aria's front-end code sends the search query.
3. The server runs its search and returns the results of the song title, artist, and actual **PATH** of the song on the music server filesystem.
4. The path is stored in the button of the returned result, as a "data" html attribute, `data-path`
5. When requesting a song, the front-end aria engine reads the `data-path` stored and sends it to the server.
6. The server forwards whatever path it receives to the stream services.

Issues include:

- The actual filesystem path is being exposed on the frontend
- In theory, anyone could tamper with the `data-path`, and request any audio file *anywhere* on the server

**Proposed 4.0 system A:**
1. A user searches a song.
2. Aria's front-end code sends the search query.
3. The server runs its search and returns the results of the song title, artist, and identification number. This number is the serial ID generated by the database on insertion.
4. The identification number can still be stored on the frontend in data. 
5. When requesting a song, the front-end Aria engine reads a `data-id` attribute and forwards this number to the request API as a POST to `/api/aria1/request`
6. Aria's request API will verify the identification number, get the song's path from the database simply by selecting by ID number, and forward the path to the stream services.

Benefits include:
- Filesystem directories are not exposed on the frontend
- Tampering with the identification data on the frontend will only potentially result in requesting another song already written in the music database.

**Comment by za419** [comment]
I like this change. Why do you prefer `.../request/{id}` over sending a request with `id` in the data fields as we do before? Just curious.

**Comment by kenellorando** [comment]
Thanks for pointing that out, my typed mistake. I still intend to send the ID as a field in the request data.

**Comment by kenellorando** [comment]
Secured in 4.0 release.
