### ISSUE TITLE
Return less sensitive, more relevant search results

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#154]
The 4.0.0 search is rudimentary in comparison to 3.0's search. At a minimum, the search should not be case sensitive. There should also be a limit on the number of returned results. 

More advanced, results should be sorted by relevancy.

**Comment by za419** [comment]
Would help. Have been a TA for northwestern's intro to databases course before. Am however temporarily (hopefully) banned from being helpful.

:(

**Comment by za419** [comment]
This issue is closed by #166.
