### ISSUE TITLE
Passively check for updates and update the database

### ISSUE THREAD

**Issue by za419** [kenellorando/cadence#158]
This is the feature which sets `cadence-dbp` apart from the legacy Node populator.

The Node populator, along with current development on `cadence-dbp`, populates the database once, when it's run. This is all that's necessary, but it would be nice to be able to update the database automatically when the music library is updated.

This would make @kenellorando's life, as Cadence's canonical administrator, much easier - Whenever he adds music to the server running the legacy code, he has to restart the server. Whenever he adds music to the server running the current populator code, he has to rerun the populator - A significant improvement, but still manual labor.

With this feature, he wouldn't need to do anything - The populator would automatically notice the modification, scan the new file, and insert it into the database, making it available for ARIA searches without any intervention.

**Comment by kenellorando** [comment]
This issue has been transferred from the `cadence-dbp` repository.

**Comment by kenellorando** [comment]
Completed in https://github.com/kenellorando/cadence/pull/216/commits/5edd2399922307dad2e3b1f38bc4d0dc36a167ee.
