### ISSUE TITLE
Make another page for the changelog

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#16]

**Comment by za419** [comment]
Suggestion: The changelog could just keep recent history (dropping old history after we get past x entries)... Git stores the full history anyway

**Comment by kenellorando** [comment]
Noted, I thought of doing this too, but there's something I like in seeing the entire list on the site itself. Also, it will be easier for people unfamiliar with using git to see how much work was put into this

**Comment by za419** [comment]
That's fair. I don't know, maybe one could write a script to run `git log` on master and generate a changelog from the response. Hmmmm......

Yeah, I don't expect your mom to understand diffs. I'm just thinking, its gonna end up being pretty messy if Cadence is being maintained (and therefore receiving updates) for a long time and there are dozens of changelog updates sitting around, both in a Git repo that's already storing history, on a filesystem that's doing the same, and (less importantly if its on a separate page) on a webpage.

**Comment by za419** [comment]
Now that I've posted it, that changelog generating script actually sounds like an interesting idea. I might write one in a separate repo, that would even give us the chance to learn to use subtrees or submodules in Cadence if that script gets used here. Any thoughts on what toolset it should use?

**Comment by za419** [comment]
What do you want the navigation to be like?

That is, suppose you're on kenellorando.com, how do we get to the changelog page?

**Comment by za419** [comment]
... Okay, now you're on cadence.kenellorando.com....

**Comment by za419** [comment]
This would be fixed by the merging of #48.
