### ISSUE TITLE
Play and pause buttons are slightly different heights

### ISSUE THREAD

**Issue by za419** [kenellorando/cadence#161]
Recommended labels: Bug, UI, good first issue.

See screenshots:

![untitled](https://user-images.githubusercontent.com/15851480/56264149-25b7fe00-60ab-11e9-8f1e-9d0b65c574e3.png)

Squashed together:

![untitled](https://user-images.githubusercontent.com/15851480/56264226-6d3e8a00-60ab-11e9-8293-51c4e2722cf3.png)

Specifically, the pause button is three pixels taller than the play button.

**Comment by kenellorando** [comment]
Potential solutions: 1. pad out the minimum height on the button 2. find a pair of ASCII characters that match in height 3. set a line-height on the `playButton` element.

**Comment by kenellorando** [comment]
Fixed by #179.

Squashed:
![image](https://user-images.githubusercontent.com/17265041/81458593-236a8b00-9169-11ea-98aa-6e4a0b47aa52.png)
