### ISSUE TITLE
[Bug] Broken autolayout on longer song titles/no artwork

### ISSUE THREAD

**Issue by rursache** [kenellorando/cadence#217]
On some longer song titles, the layout seems to break. I would also suggest a default artwork for the songs that don't have one.

![image](https://i.imgur.com/M6M4Ddl.png)

**Comment by kenellorando** [comment]
Thanks for the find. I'll see what I can do about this one before I do the next release.

**Comment by kenellorando** [comment]
Fixed in https://github.com/kenellorando/cadence/commit/c4f2df1f9bec6ed940ec320de67c345b4077be66.
