### ISSUE TITLE
Add note to README about git-lfs

### ISSUE THREAD

**Issue by za419** [kenellorando/cadence#34]
Since the repo won't clone correctly without it

**Comment by za419** [comment]
No one sees the first commit here either.

**Comment by kenellorando** [comment]
What do you mean regarding the repo cloning?

**Comment by za419** [comment]
If the repo is cloned without git-lfs, to my understanding, iss.mp4 and iss-mobile.mp4 will both be small text files. iss.mp4 will read:

    version https://git-lfs.github.com/spec/v1
    oid sha256:75185d01dd2626d8d5e826f8731dfde6825ba652477d314ae707b896c1e07656
    size 46945228

and iss-mobile.mp4 will read 

    version https://git-lfs.github.com/spec/v1
    oid sha256:28feb1de13c3534dcaacc311f00bb2f623cd4c85692d5dadc4041750963b22f2
    size 23674147

This is clearly not desirable.
