### ISSUE TITLE
Lightmage background 'stutters' once per second

### ISSUE THREAD

**Issue by za419** [kenellorando/cadence#55]
![cornyshinygermanshepherd](https://cloud.githubusercontent.com/assets/15851480/26747754/91ae447e-47bd-11e7-86c0-bb33b36dd22a.gif)

Or in [fancy-schmancy hi-res](https://gfycat.com/CornyShinyGermanshepherd)

**Comment by kenellorando** [comment]
Added the fallback image as a second thought but didn't see this blatant bug. Fast catch, as usual.

also, Kali?  ‎😏 ‎😏

**Comment by za419** [comment]
I pay attention.... sometimes.

Yes, Kali! I, of course, lost the thumb drive that had it.... 😧

I totally couldn't ever use that again........... 🤔
