### ISSUE TITLE
body does not resize on widest screens for YoRHa, Mayberry, and Electromaster

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#58]
No visible reduction in size on the widest screens despite the fact that this code is in base.css:
```
@media (min-height: 43em) and (min-width: 85em) {
  body {
    padding-left: 13em;
    padding-right: 12em;
  }
}
```

**Comment by kenellorando** [comment]
I thought I already fixed this... -__-

**Comment by za419** [comment]
[Resizing YoRHa](https://gfycat.com/gifs/detail/QueasyEmbellishedEarthworm)

IDK, it looks OK to me
