### ISSUE TITLE
Use of ".fullscreen-bg {display: none;}" in base.css is unknown

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#59]
Need to test what this does and see if can be removed

**Comment by za419** [comment]
Uhh... Ken? Is you drugs?

That item is hiding the container used for video themes. Removing it might cause issues with video themes sticking around until the page is refreshed (if you select a non-video theme)... But its more of a failsafe, making sure that if the theme engine messes up and leaves a video running, the browser will still not display it

**Comment by kenellorando** [comment]
@za419 I am aware of all that. I remember the bugs we experienced using the old Space Station theme.

Last night I tried removing it and looked to see if the video bug was there using the live-preview feature of my editor but I couldn't detect any problems. I thought perhaps we did something different in Light Mage which fixed the problem.

To be sure it could be removed, I wanted to test again without the editor's preview. I've just tested it without the property on the server and the bug showed itself again. That's all
