### ISSUE TITLE
Replace onclicks in html, on "click"s in js with event listeners

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#60]

**Comment by za419** [comment]
*sighhhh*

I mean, I know that this is technically better practice, and that `addEventListener` is generally a better way to handle events, but...

Geez, this is gonna be a lot of work. Gross.

**Comment by za419** [comment]
Mine or yours?

**Comment by kenellorando** [comment]
I'll take care of this lol. You should focus on naming your VCS. My personal suggestion is "Odin" after your name and the Norse god. You should also find a profile picture.

**Comment by kenellorando** [comment]
Assigned to @jakobfrank

**Comment by za419** [comment]
@JakobFrank is sitting in a chair not having his laptop and therefore not working on his PR.

*hopes decreasing*
