### ISSUE TITLE
Create a start script

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#63]
Edit 2019-02-23:

The start script will save time by automating all of the following Cadence admin tasks into a single script.
1. Kill and start Icecast in the background
2. Kill and start Liquidsoap in the background
3. Initialize all webserver configuration in environment variables
4. Start the webserver

**Comment by za419** [comment]
which does...?

**Comment by za419** [comment]
kennnnnnnnn

**Comment by kenellorando** [comment]
I will finally create the all-in one start script with the release of 4.0.

**Comment by kenellorando** [comment]
Now in progress. This start script will optionally start the source and stream servers. After that, it will call a separate configuration script, which sets environment variables used as server configuration. Finally, it will run the `.go` files (or binary, maybe) to start the server.

**Comment by za419** [comment]
I vote binary

**Comment by kenellorando** [comment]
Created for 4.0 release.
