### ISSUE TITLE
Find way to write drop and add database indexes within index.js

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#69]
Commands do not seem to work in index.js. They must be run through the database console to enable text indexes.
```
      // Drop old indexes
      db.collection("music").dropIndexes();
      // Enable text searching
      db.executeDbAdminCommand({
        setParameter: 1,
        textSearchEnabled: true
      });
      // Set search index
      db.collection("music").createIndex({
        title: "text",
        artist: "text",
        album: "text"
      });
```

**Comment by kenellorando** [comment]
Going to leave this documentation here for future reference.
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/

**Comment by za419** [comment]
Do you need to enter some credentials for administrating the database?

**Comment by kenellorando** [comment]
No, no credentials required
