### ISSUE TITLE
Volume bar looks like trash on Android Firefox

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#7]

**Comment by za419** [comment]
I installed Firefox on my phone just to see what this looks like, and @kenellorando is definitely not wrong.

For reference, this is the page on my laptop (Chrome for Windows 10):
![image](https://cloud.githubusercontent.com/assets/15851480/24439693/6eddac5e-1415-11e7-9850-b47a5dd87e87.png)

This is the page on my phone (Firefox for Android 5.0.1 "Lollipop"):

![screenshot_2017-03-29-00-18-41](https://cloud.githubusercontent.com/assets/15851480/24439751/c62a20be-1415-11e7-80ce-301f0c33ab25.png)

**Comment by za419** [comment]
Honestly, it looks to me like Firefox is just applying a background to `#volume`. Maybe if base.css overrode it with a transparent background?

**Comment by za419** [comment]
Wait, does this look good on desktop Firefox?

**Comment by za419** [comment]
For some reason, `chicago-evening` has a bit of transparency, but both `cyberpunk-bartender` (night) and `YoRHa` have opaque volume bars. This might give a path to a solution.

**Comment by za419** [comment]
@kenellorando and I think this is because both `YoRHa` and `cyberpunk-bartender` set the body to be completely opaque, while `chicago-evening` inherits the partial transparency set in `base.css`. Probably not helpful then.
