### ISSUE TITLE
Display (next few) requested songs

### ISSUE THREAD

**Issue by za419** [kenellorando/cadence#73]
Can just be a table, showing the next n≤4 songs that Cadence has been requested to play, or a message saying "No requests waiting", but I think this information should be available client-side.

**Comment by kenellorando** [comment]
This would be in the domain of liquidsoap. And while that software does not look as far forward as `n+4`, it does appear to be possible to `n+1` with some trickery: https://github.com/savonet/liquidsoap/issues/1658

This sort of implementation would require cadence to read some liquidsoap file that I force it to log on the server.
