### ISSUE TITLE
Song request file names with quotes fail to be passed correctly

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#74]
Presumably both single and double quotes.
Requesting "sister's noise" server log:
```
Received: {"path":"/home/ken/Music/fripSide/01. sister"}
```

(note to self, I've removed the single quote from the filename for now, because I want to request this song.. for future testing, maybe use Sweet Child O'mine)

**Comment by za419** [comment]
Hm. Try `encodeURIComponent` on the client side, then undoing that on the server?
