### ISSUE TITLE
[FEATURE REQUEST] Chibi Anime theme

### ISSUE THREAD

**Issue by za419** [kenellorando/cadence#96]
As requested by @KarenwithaKay.

"Kawaii chibi anime stickers all over a black or pink background"

Again, I'll work with her. She's the designer.

**Comment by kenellorando** [comment]
@Karenwithakay 
- If I were to create a background image for Cadence, what dimensions should it be?
Doesn't matter, as long as it looks clear on large screens with the image-fit that you use like `background-size` or `background-position`. Style of the art in the image matters; a small background image of pixel-art looks fine on a large screen but a picture of a city will not. 

- Do we care about the mobile site shiz?
The base CSS is set to take care of the elements on the page for mobile view so you would only have to worry about elements specific to your theme. For example if you want to use different pictures for mobile view and desktop view, you would achieve this by setting the desktop view `background-image` in a media query for desktop sizes. @za419 can show you how to do this very well.

- What is the URL for the easy-access fonts?
I find all of my fonts on https://fonts.google.com/ 

- I need a list of animus one would like referenced in this theme.
Characters: Lux, 2B, Mikoto Misaka
Actually, each of these characters already have a dedicated theme. If you haven't seen them yet @za419 can show you how to access them on a console.

**Comment by magix430** [comment]
- Fonts should **not** be monospace or sans serif (fit to theme of Chibi). Here are a few good ones:
    - https://fonts.google.com/specimen/Gloria+Hallelujah (Gloria Hallelujah: script, handwriting)
    - https://fonts.google.com/specimen/Gamja+Flower/ (Gamja Flower: handwriting, standard)
    - https://fonts.google.com/specimen/Poiret+One/ (Poiret One: typeset)
    - https://fonts.google.com/specimen/Gaegu/ (Gaegu: similar to Gamja and Gloria)
- Chibi anime should most likely fit a theme where the character has origins in something cutesy. Unfortunately, 2B doesn't quite fit because her theme is more "thicc" and appeals to be sexy. If you were to take something from the Nier:Automata series, Operator would have a better role.
    - Lucky Star
    - Mayo Chiki (though finding fanart for this is difficult, it's an obscure but quality anime)
    - Poyopoyo
    - Acchi Kocchi (sample pics: https://goo.gl/UE8M5p)
- aim for wallpaper size (1920x1080) for most chibi wallpaper images, commit for using the smaller images for mobile (different galleries depending on platform) if possible

**Comment by za419** [comment]
We can do the mobile switch pretty easily (either as a separate theme from the theme engine's point of view as on `space-station`/`earth` or with the screen width attributes as on `yorha`). Platform dependence would require the callback system Ive been toying with, I'm sure I could get it working fairly quickly though
