### ISSUE TITLE
Dropdown menu opens without hovering the button

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/cadence#99]
Hovering the cursor in the area directly below the "Select Theme" box shows the theme list, whereas the expected behavior is to only show the list when hovering the "Select Theme" box itself.

**Comment by kenellorando** [comment]
@jakobfrank 
An ideal assignment for @jakobfrank

**Comment by za419** [comment]
Agreed, although I will see if I can figure it out by myself for educational purposes... @kenellorando 

Should @JakobFrank do this before or after he takes care of #60 ?

**Comment by za419** [comment]
That would probably be a good, yes

@JakobFrank

**Comment by kenellorando** [comment]
Closed in 7372635672018405432d09c58d7a4d10e5011342 by changing the hiding mechanism, which previously switched the opacity on hover between 0 and 1. Fix sets `display: none` on the `.dropdown-content` by default, switching to `display: block` on `.dropdown:hover`
